command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

# Environment variables - set these in Databricks Apps UI > Settings > Environment Variables
# Required:
#   LAKEBASE_PASSWORD - Your Databricks Personal Access Token (starts with 'dapi')
#
# Note: Secret references like ${secrets.scope.key} are not expanding properly
# in this Databricks Apps environment, so set the actual token value in the UI
